open mode "rU" throws an error in python 3.11; changed to "r"
```
/kmax/alg.py", line 1099, in extract
    makefile = open(makefile, "rU")
               ^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU'
```